// <auto-generated />
using System;
using Car_Salon_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Salon_App.Migrations
{
    [DbContext(typeof(CarSalonDbContext))]
    [Migration("20240925182518_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Salon_App.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("Car_Salon_App.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EngineId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Discount = 10,
                            EngineId = 1,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVPmQmyQY3Y5l_OU-xBQ7gGe2TXtKLX5pFPA&s",
                            Model = "Q5",
                            Price = 21000m,
                            Quantity = 5,
                            Year = new DateTime(2016, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            CategoryId = 2,
                            Discount = 5,
                            EngineId = 15,
                            ImageUrl = "https://cdn3.riastatic.com/photosnew/auto/photo/mercedes-benz_cls-class__486325818f.jpg",
                            Model = "CLS",
                            Price = 30000m,
                            Quantity = 2,
                            Year = new DateTime(2013, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 4,
                            Discount = 15,
                            EngineId = 6,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqzKVeLR9AsFHMTk35UJYKqspSYu8t1NyjCg&s",
                            Model = "525I",
                            Price = 5500m,
                            Quantity = 10,
                            Year = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Car_Salon_App.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Station wagon"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hatchback"
                        });
                });

            modelBuilder.Entity("Car_Salon_App.Entities.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2.0,
                            Type = "Diesel"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2.0,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3.0,
                            Type = "Diesel"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 3.0,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 5.0,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 2.5,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 2.5,
                            Type = "Diesel"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 1.3999999999999999,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 1.6000000000000001,
                            Type = "Diesel"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 5.0,
                            Type = "Diesel"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 2.2000000000000002,
                            Type = "Diesel"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 2.7000000000000002,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 1.8,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 1.8999999999999999,
                            Type = "Diesel"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 5.5,
                            Type = "Petrol"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 4.7000000000000002,
                            Type = "Petrol"
                        });
                });

            modelBuilder.Entity("Car_Salon_App.Entities.Car", b =>
                {
                    b.HasOne("Car_Salon_App.Entities.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Salon_App.Entities.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Salon_App.Entities.Engine", "Engine")
                        .WithMany("Cars")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("Car_Salon_App.Entities.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Car_Salon_App.Entities.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Car_Salon_App.Entities.Engine", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
